---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "ShipIt Taskcluster service"
consumes:
  - application/json
produces:
  - application/json
paths:

  /steps:
    get:
      operationId: "shipit_taskcluster.api.list_taskcluster_steps"
      description: List all Taskcluster steps with status
      parameters:
        - name: state
          in: query
          required: false
          default: running
          type: string
      responses:
        200:
          description: List of all steps

#  /steps/{uid}/status:
#
#    get:
#      operationId: "shipit_taskcluster.api.get_step_status"
#      description: Status of a Taskcluster step
#      parameters:
#        - $ref: "#/parameters/uid"
#      responses:
#        200:
#          description: Status of a Taskcluster step
#          schema:
#            $ref: '#/definitions/StepResult'

  /steps/{uid}:
    put:
      operationId: "shipit_taskcluster.api.create_taskcluster_step"
      description: Create new Taskcluster step
      parameters:
        - name: uid
          in: path
          description: Step UID
          required: true
          type: string
        - name: body
          in: body
          description: inputs to create Taskcluster step
          required: true
          schema:
            $ref: '#/definitions/Taskcluster'
      responses:
        200:
          description: Returns nothing
          schema:
            type: string
        409:
          description: "A step with this uid or task_group_id already exists"
#
#    delete:
#      operationId: "shipit_taskcluster.api.delete_step"
#      description: Remove a Taskcluster step
#      parameters:
#        - $ref: '#/parameters/uid'
#      responses:
#        200:
#          description: Removal of Taskcluster step

definitions:

  # Step and StepResult definitions seem generic enough that they should be defined in a more global
  # location for all shipit services that represent a step
#  StepResult:
#    type: object
#    required:
#      - state
#    properties:
#      state:
#        type: string
#        enum:
#          - in_progress
#          - success
#          - failed
#          - cancelled
#      message:
#        type: string
#        description: More elaborate description of state for humans.
#      output:
#        $ref: '#/definitions/Output'

#  Step:
#    type: object
#    required:
#      - uid
#      - input
#      - parameters
#    properties:
#      uid:
#        type: string
#      input:
#        $ref: '#/definitions/Input'
#      parameters:
#        $ref: '#/definitions/Parameters'

  Taskcluster:
    type: object
    description: A representation of Taskcluster group of Tasks
    required:
      - taskGroupId
    properties:
      taskGroupId:
        type: string
        description: the group id that is shared between tasks

#  Parameters:
#    type: object
#
#  Input:
#    type: object
#
#  Output:
#    type: object

#parameters:
#  uid:
#    name: uid
#    in: path
#    description: Step UID
#    required: true
